<a href="https://colab.research.google.com/github/vaishnavi-devadiga-20/waterprediction/blob/main/project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install nltk pandas scikit-learn

Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (3.9.2)
Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (1.6.1)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\Hp\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [ ]:
!python -m pip install nltk pandas scikit-learn

Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (3.9.2)
Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (1.6.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from click->nltk) (0.4.6)

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\Hp\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [ ]:
import pandas as pd
import nltk
import sqlite3
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [ ]:
data = {
    "food_item": [
        "idli","dosa","vada","roti","meals",
        "veg biriyani","egg biriyani","chicken biriyani",
        "mutton biriyani","ice cream","noodles",
        "orange juice","apple juice","pineapple juice","banana juice"
    ],

    "review":[
        "soft and tasty",
        "very crispy and good",
        "delicious snack",
        "good taste",
        "very healthy",
        "very tasty",
        "good flavor",
        "excellent taste",
        "very spicy and tasty",
        "sweet and nice",
        "good noodles",
        "fresh juice",
        "sweet apple taste",
        "very fresh pineapple",
        "good banana juice"
    ],

    "sentiment":[
        "positive","positive","positive","positive","positive",
        "positive","positive","positive","positive","positive",
        "positive","positive","positive","positive","positive"
    ]
}

df = pd.DataFrame(data)
df.head()

  food_item                review sentiment
0      idli        soft and tasty  positive
1      dosa  very crispy and good  positive
2      vada       delicious snack  positive
3      roti            good taste  positive
4     meals          very healthy  positive

In [ ]:
X = df['review']
y = df['sentiment']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
vectorizer = CountVectorizer()

x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

In [ ]:
model = MultinomialNB()
model.fit(x_train_vec,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(x_test_vec)

print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 1.0

In [ ]:
conn = sqlite3.connect("food_reviews.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS reviews(
food TEXT,
review TEXT,
sentiment TEXT
)
""")

conn.commit()

In [ ]:
for i in range(len(df)):
    cursor.execute("INSERT INTO reviews VALUES (?,?,?)",
                   (df.food_item[i],df.review[i],df.sentiment[i]))

conn.commit()

In [ ]:
query = "SELECT food, COUNT(review) FROM reviews GROUP BY food"
result = pd.read_sql(query,conn)

result

                food  COUNT(review)
0        apple juice              1
1       banana juice              1
2   chicken biriyani              1
3               dosa              1
4       egg biriyani              1
5          ice cream              1
6               idli              1
7              meals              1
8    mutton biriyani              1
9            noodles              1
10      orange juice              1
11   pineapple juice              1
12              roti              1
13              vada              1
14      veg biriyani              1